// Interface copy is translated at the text-node level so stored task content and form values stay untouched.
export const languages = { ru: 'Русский', kk: 'Қазақша', en: 'English' };

const phrases = {
  'Каталог': ['Catalog', 'Каталог'], 'Мои предложения': ['My proposals', 'Менің ұсыныстарым'], 'Черновики': ['Drafts', 'Нобайлар'], 'Как это работает': ['How it works', 'Қалай жұмыс істейді'],
  'Студент': ['Student', 'Студент'], 'Заказчик': ['Client', 'Тапсырыс беруші'], 'Включить светлую тему': ['Use light theme', 'Ашық тақырыпты қосу'], 'Включить тёмную тему': ['Use dark theme', 'Қараңғы тақырыпты қосу'],
  'Проверка OpenAI…': ['Checking OpenAI…', 'OpenAI тексерілуде…'], 'Ключ OpenAI задан': ['OpenAI key configured', 'OpenAI кілті орнатылған'], 'Демо вопросы': ['Demo questions', 'Демо сұрақтар'], 'Сервер недоступен': ['Server unavailable', 'Сервер қолжетімсіз'],
  'Запустите приложение через сервер': ['Start the app through the server', 'Қолданбаны сервер арқылы іске қосыңыз'], 'Если страница открыта как файл, каталог не загрузится. Запустите': ['If this page is opened as a file, the catalog will not load. Run', 'Бет файл ретінде ашылса, каталог жүктелмейді. Іске қосыңыз'], 'в папке проекта, затем откройте': ['in the project folder, then open', 'жоба қалтасында, содан кейін ашыңыз'],
  'HackAlem AI · практические задачи': ['HackAlem AI · practical tasks', 'HackAlem AI · практикалық тапсырмалар'], 'Задачи для студенческих команд': ['Tasks for student teams', 'Студенттік командаларға арналған тапсырмалар'], 'Выберите задачу для команды': ['Choose a task for your team', 'Командаңызға тапсырма таңдаңыз'],
  'Уточняйте карточки, сравнивайте предложения и подтверждайте результат работы.': ['Refine task cards, compare proposals, and confirm results.', 'Тапсырма карточкаларын нақтылап, ұсыныстарды салыстырып, нәтижені растаңыз.'],
  'Каталог открыт всем командам. Решение о сотрудничестве принимает заказчик.': ['All teams can browse the catalog. The client chooses who to work with.', 'Каталог барлық командаларға ашық. Ынтымақтастық туралы шешімді тапсырыс беруші қабылдайды.'],
  'Сбросить демо': ['Reset demo', 'Демоны қалпына келтіру'], '＋ Создать задачу': ['＋ Create task', '＋ Тапсырма жасау'], 'Выбрать команду': ['Choose team', 'Команданы таңдау'],
  'Рейтинг отражает готовность задачи': ['The score shows task readiness', 'Рейтинг тапсырманың дайындығын көрсетеді'], 'Предлагайте решение самостоятельно': ['Propose your own solution', 'Өз шешіміңізді ұсыныңыз'],
  'Баллы начисляются за сведения, которые вы проверили и подтвердили. Чем полнее карточка, тем выше она в каталоге.': ['Points are awarded for information you review and confirm. More complete cards rank higher in the catalog.', 'Ұпайлар сіз тексеріп, растаған мәліметтер үшін беріледі. Карточка неғұрлым толық болса, каталогта соғұрлым жоғары тұрады.'],
  'Откройте любую задачу, отправьте идею и план. После выбора команды можно показать этап работы на подтверждение.': ['Open any task and send an idea and plan. Once selected, your team can submit work stages for approval.', 'Кез келген тапсырманы ашып, идея мен жоспар жіберіңіз. Команда таңдалған соң жұмыс кезеңдерін растауға ұсына аласыз.'],
  'Открытый каталог': ['Open catalog', 'Ашық каталог'], 'Найти задачу': ['Find a task', 'Тапсырманы іздеу'], 'Поиск по задачам': ['Search tasks', 'Тапсырмаларды іздеу'], 'Все задачи': ['All tasks', 'Барлық тапсырмалар'], 'Все уровни': ['All levels', 'Барлық деңгейлер'], 'Уровень готовности': ['Readiness level', 'Дайындық деңгейі'],
  'Веб-разработка': ['Web development', 'Веб-әзірлеу'], 'Дизайн': ['Design', 'Дизайн'], 'Исследование': ['Research', 'Зерттеу'],
  'Черновик': ['Draft', 'Нобай'], 'Рабочая': ['In progress', 'Жұмыс үстінде'], 'Готовая': ['Ready', 'Дайын'], 'Приоритетная': ['Priority', 'Басым'],
  'Задачи не найдены. Измените фильтр или поиск.': ['No tasks found. Change the filter or search.', 'Тапсырмалар табылмады. Сүзгіні немесе іздеуді өзгертіңіз.'],
  'Следующая цель заказчика': ['Client’s next goal', 'Тапсырыс берушінің келесі мақсаты'], 'Приоритетный уровень достигнут.': ['Priority level reached.', 'Басым деңгейге жетті.'], 'Максимальный уровень достигнут.': ['Maximum level reached.', 'Ең жоғары деңгейге жетті.'], 'Максимальный уровень': ['Maximum level', 'Ең жоғары деңгей'],
  'Следующий уровень:': ['Next level:', 'Келесі деңгей:'], 'Добавьте:': ['Add:', 'Қосыңыз:'], 'Все сведения заполнены и подтверждены.': ['All details are complete and confirmed.', 'Барлық мәлімет толтырылып, расталды.'], 'Последнее изменение:': ['Last change:', 'Соңғы өзгеріс:'], 'Улучшить задачу →': ['Improve task →', 'Тапсырманы жақсарту →'],
  'Прогресс задачи': ['Task progress', 'Тапсырма ілгерілеуі'], 'Прогресс команды': ['Team progress', 'Команда ілгерілеуі'], 'уровень': ['level', 'деңгей'], 'До следующего уровня осталось': ['XP to next level:', 'Келесі деңгейге дейінгі XP:'],
  '+10 XP за подтверждённый этап (до трёх на работу) · +30 XP после завершения работы заказчиком. За просмотр и отправку предложения опыт не начисляется.': ['+10 XP per approved stage (up to three per job) · +30 XP when the client completes the job. Viewing and sending a proposal earn no XP.', 'Расталған әр кезеңге +10 XP (бір жұмысқа үшеуге дейін) · тапсырыс беруші жұмысты аяқтағанда +30 XP. Қарау мен ұсыныс жіберу XP бермейді.'],
  'Ранги и награды команды': ['Team ranks and rewards', 'Команда дәрежелері мен марапаттары'], 'Ранги и награды': ['Ranks and rewards', 'Дәрежелер мен марапаттар'], 'Ранги открываются по XP; награды — за подтверждённые результаты.': ['Ranks unlock with XP; rewards come from approved results.', 'Дәрежелер XP арқылы, марапаттар расталған нәтижелер арқылы ашылады.'],
  'Практики': ['Practitioners', 'Тәжірибешілер'], 'Профи': ['Pros', 'Кәсіпқойлар'], 'Эксперты': ['Experts', 'Сарапшылар'], 'Первый шаг': ['First step', 'Алғашқы қадам'], 'Результат': ['Result', 'Нәтиже'], 'Полный цикл': ['Full cycle', 'Толық цикл'],
  'Подтверждён первый этап': ['First stage approved', 'Алғашқы кезең расталды'], 'Завершена первая работа': ['First job completed', 'Алғашқы жұмыс аяқталды'], 'Три этапа и завершение': ['Three stages and completion', 'Үш кезең және аяқталу'], 'Текущий': ['Current', 'Ағымдағы'], 'открыт': ['unlocked', 'ашылған'], 'закрыт': ['locked', 'құлыпталған'], 'получена': ['earned', 'алынған'], 'не получена': ['not earned', 'алынбаған'], 'закрыта': ['locked', 'құлыпталған'],
  'Рекомендации для команды': ['Team recommendations', 'Командаға ұсыныстар'], 'Подбор по навыкам и интересам': ['Matched by skills and interests', 'Дағдылар мен қызығушылықтар бойынша'], 'подходящие задачи': ['matching tasks', 'сәйкес тапсырмалар'], 'Причины совпадения показаны в карточках. Полный каталог открыт ниже.': ['Each card shows why it matches. The full catalog is below.', 'Әр карточкада сәйкестік себебі көрсетілген. Толық каталог төменде.'],
  'Навыки:': ['Skills:', 'Дағдылар:'], 'Интерес:': ['Interest:', 'Қызығушылық:'], 'Предложение уже отправлено': ['Proposal already sent', 'Ұсыныс жіберілген'], 'Открыть задачу →': ['Open task →', 'Тапсырманы ашу →'], 'Совпадений пока нет. Все задачи доступны в каталоге ниже.': ['No matches yet. All tasks are available in the catalog below.', 'Әзірге сәйкестік жоқ. Барлық тапсырма төмендегі каталогта бар.'],
  'в каталоге': ['in catalog', 'каталогта'], 'Приоритетная задача · верхний уровень': ['Priority task · top level', 'Басым тапсырма · ең жоғары деңгей'], 'Выбраны:': ['Selected:', 'Таңдалғандар:'], 'Подробнее →': ['Details →', 'Толығырақ →'],
  'Работа заказчика': ['Client workspace', 'Тапсырыс беруші бөлімі'], 'Черновики задач': ['Task drafts', 'Тапсырма нобайлары'], 'Дополните сведения и подтвердите карточку перед публикацией.': ['Add details and confirm the card before publishing.', 'Жариялар алдында мәліметтерді толықтырып, карточканы растаңыз.'], '＋ Новый черновик': ['＋ New draft', '＋ Жаңа нобай'], 'Черновик без названия': ['Untitled draft', 'Атаусыз нобай'], 'Продолжить →': ['Continue →', 'Жалғастыру →'], 'Черновиков пока нет.': ['No drafts yet.', 'Әзірге нобай жоқ.'],
  'Сквозной сценарий': ['End-to-end flow', 'Толық сценарий'], 'Как устроен «Старт»': ['How “Start” works', '«Старт» қалай жұмыс істейді'], 'От слабого описания до подтверждённого этапа работы.': ['From a rough description to an approved work stage.', 'Қысқаша сипаттамадан расталған жұмыс кезеңіне дейін.'], 'Шаг': ['Step', 'Қадам'],
  'Заказчик создаёт черновик': ['Client creates a draft', 'Тапсырыс беруші нобай жасайды'], 'Вводит свободное описание и сохраняет его.': ['Enters a free-form description and saves it.', 'Еркін сипаттама енгізіп, сақтайды.'], 'Система задаёт 3 вопроса': ['The system asks 3 questions', 'Жүйе 3 сұрақ қояды'], 'Ответы попадают в редактируемую карточку.': ['Answers enter an editable card.', 'Жауаптар өңделетін карточкаға түседі.'], 'Рейтинг меняет позицию': ['Score changes catalog position', 'Рейтинг каталогтағы орынды өзгертеді'], 'Подтверждённая задача публикуется в общем каталоге.': ['A confirmed task is published in the shared catalog.', 'Расталған тапсырма ортақ каталогта жарияланады.'], 'Команды предлагают решения': ['Teams propose solutions', 'Командалар шешім ұсынады'], 'Любая команда видит задачи и отправляет план.': ['Any team can view tasks and send a plan.', 'Кез келген команда тапсырмаларды көріп, жоспар жібере алады.'], 'Заказчик выбирает вручную': ['The client selects teams', 'Тапсырыс беруші өзі таңдайды'], 'Можно выбрать несколько команд или никого.': ['Select several teams or none.', 'Бірнеше команданы таңдауға немесе ешкімді таңдамауға болады.'], 'Опыт за результат': ['XP for results', 'Нәтиже үшін тәжірибе'], 'Команда получает 10 XP за каждый из трёх подтверждённых этапов и ещё 30 XP после завершения работы заказчиком.': ['The team earns 10 XP for each of three approved stages and another 30 XP when the client marks the job complete.', 'Команда үш расталған кезеңнің әрқайсысына 10 XP және тапсырыс беруші жұмысты аяқтағанда тағы 30 XP алады.'],
  'Контекст и потребность': ['Context and need', 'Мәнмәтін және қажеттілік'], 'Данные и материалы': ['Data and materials', 'Деректер мен материалдар'], 'Ожидаемый результат': ['Expected result', 'Күтілетін нәтиже'], 'Критерии успеха': ['Success criteria', 'Табыс критерийлері'], 'Ограничения': ['Constraints', 'Шектеулер'], 'Пользователи': ['Users', 'Пайдаланушылар'], 'Контакт и формат связи': ['Contact and communication', 'Байланыс және қарым-қатынас түрі'],
  'Что происходит сейчас и что нужно изменить?': ['What is happening now, and what needs to change?', 'Қазір не болып жатыр және нені өзгерту керек?'], 'Какие данные, примеры или источники доступны?': ['What data, examples, or sources are available?', 'Қандай деректер, мысалдар немесе дереккөздер бар?'], 'Что команда должна подготовить?': ['What should the team deliver?', 'Команда не дайындауы керек?'], 'По каким измеримым признакам вы примете результат?': ['What measurable criteria will you use to accept the result?', 'Нәтижені қандай өлшенетін көрсеткіштермен қабылдайсыз?'], 'Какие сроки, технологии и доступы важны?': ['What deadlines, technologies, and access matter?', 'Қандай мерзім, технология және қолжетімділік маңызды?'], 'Для кого создаётся решение?': ['Who is the solution for?', 'Шешім кім үшін жасалады?'], 'Кто даст обратную связь, как и когда?': ['Who will give feedback, how, and when?', 'Кері байланысты кім, қалай және қашан береді?'],
  'Редактирование': ['Editing', 'Өңдеу'], 'Новая задача': ['New task', 'Жаңа тапсырма'], 'Карточка бизнес задачи': ['Business task card', 'Бизнес тапсырма карточкасы'], 'Начните со свободного описания и уточните детали.': ['Start with a free-form description, then add details.', 'Алдымен еркін сипаттама беріп, кейін мәліметтерді нақтылаңыз.'], 'Помощник по созданию задачи': ['Task creation assistant', 'Тапсырма жасау көмекшісі'],
  'Опишите задачу своими словами. Этого достаточно, чтобы сохранить черновик. Помощник предложит поля и три вопроса для дальнейшего уточнения.': ['Describe the task in your own words. That is enough to save a draft. The assistant will suggest fields and three follow-up questions.', 'Тапсырманы өз сөзіңізбен сипаттаңыз. Нобайды сақтау үшін осы жеткілікті. Көмекші өрістер мен үш нақтылау сұрағын ұсынады.'],
  'Свободное описание': ['Free-form description', 'Еркін сипаттама'], 'Что происходит сейчас, какой результат нужен и что уже известно?': ['What is happening now, what result is needed, and what is already known?', 'Қазір не болып жатыр, қандай нәтиже қажет және не белгілі?'], 'Составить черновик': ['Prepare draft', 'Нобай құрастыру'], 'Подготавливаем черновик…': ['Preparing draft…', 'Нобай дайындалуда…'], 'Название задачи': ['Task title', 'Тапсырма атауы'], 'Что нужно решить?': ['What needs to be solved?', 'Нені шешу керек?'],
  'Тема': ['Topic', 'Тақырып'], 'Срок': ['Deadline', 'Мерзім'], 'Например, 2 недели': ['For example, 2 weeks', 'Мысалы, 2 апта'], 'Навыки команды': ['Team skills', 'Команда дағдылары'], 'Figma, React, интервью': ['Figma, React, interviews', 'Figma, React, сұхбат'], 'Подтверждаю точность заполненных сведений и публикацию карточки.': ['I confirm the information is accurate and approve publishing this card.', 'Мәліметтердің дұрыстығын және карточканы жариялауды растаймын.'],
  'Предварительный рейтинг': ['Estimated score', 'Алдын ала рейтинг'], 'Следующее поле:': ['Next field:', 'Келесі өріс:'], 'Все семь критериев засчитаны.': ['All seven criteria count.', 'Барлық жеті критерий есептелді.'], 'Все критерии засчитаны.': ['All criteria count.', 'Барлық критерий есептелді.'], 'Для роста рейтинга уточните:': ['To raise the score, clarify:', 'Рейтингті көтеру үшін нақтылаңыз:'], 'Карточка готова к публикации.': ['The card is ready to publish.', 'Карточка жариялауға дайын.'], 'Для публикации отметьте подтверждение выше.': ['Check the confirmation above to publish.', 'Жариялау үшін жоғарыдағы растауды белгілеңіз.'],
  'Получить 3 уточняющих вопроса': ['Get 3 follow-up questions', '3 нақтылау сұрағын алу'], 'Сохранить черновик': ['Save draft', 'Нобайды сақтау'], 'Сохранить карточку': ['Save card', 'Карточканы сақтау'], 'Опубликовать': ['Publish', 'Жариялау'], 'Изменения сохранены в этом браузере.': ['Changes saved in this browser.', 'Өзгерістер осы браузерде сақталды.'], 'Изменения сохраняются в этом браузере автоматически.': ['Changes are saved automatically in this browser.', 'Өзгерістер осы браузерде автоматты сақталады.'], 'Начать заново': ['Start over', 'Қайта бастау'], 'Локальный черновик удалён. Новые изменения сохраняются автоматически.': ['Local draft removed. New changes save automatically.', 'Жергілікті нобай жойылды. Жаңа өзгерістер автоматты сақталады.'],
  'Предложения OpenAI': ['OpenAI suggestions', 'OpenAI ұсыныстары'], 'Демо черновик без OpenAI': ['Demo draft without OpenAI', 'OpenAI жоқ демо нобай'], 'Проверьте факты и выберите поля для добавления. Пустые поля ИИ оставил без догадок.': ['Check the facts and select fields to add. The AI left unknown fields blank.', 'Деректерді тексеріп, қосылатын өрістерді таңдаңыз. Белгісіз өрістерді AI бос қалдырды.'], 'Без API-ключа описание предложено только как контекст; остальные поля нужно уточнить.': ['Without an API key, only the description is suggested as context; clarify the other fields.', 'API кілтінсіз сипаттама тек мәнмәтін ретінде ұсынылады; қалған өрістерді нақтылау керек.'], 'Из описания пока нечего перенести. Дополните текст и попробуйте снова.': ['Nothing to extract yet. Add detail and try again.', 'Әзірге алатын мәлімет жоқ. Мәтінді толықтырып, қайта көріңіз.'],
  'Добавить выбранное в карточку': ['Add selected fields to card', 'Таңдалған өрістерді карточкаға қосу'], 'Уточняющие вопросы:': ['Follow-up questions:', 'Нақтылау сұрақтары:'], 'Ваш ответ ·': ['Your answer ·', 'Сіздің жауабыңыз ·'], 'Добавить ответы в карточку': ['Add answers to card', 'Жауаптарды карточкаға қосу'], 'Выбранные предложения добавлены. Проверьте карточку перед публикацией.': ['Selected suggestions added. Review the card before publishing.', 'Таңдалған ұсыныстар қосылды. Жариялар алдында карточканы тексеріңіз.'], 'Ответы добавлены. Проверьте их перед публикацией.': ['Answers added. Review them before publishing.', 'Жауаптар қосылды. Жариялар алдында тексеріңіз.'], 'Демо вопросы по незаполненным полям': ['Demo questions for missing fields', 'Толтырылмаған өрістерге демо сұрақтар'], 'Вопросы OpenAI': ['OpenAI questions', 'OpenAI сұрақтары'], 'Ответы можно проверить до публикации.': ['You can review answers before publishing.', 'Жауаптарды жариялар алдында тексере аласыз.'],
  'Выбранные предложения добавлены.': ['Selected suggestions added.', 'Таңдалған ұсыныстар қосылды.'], 'Черновик сохранён.': ['Draft saved.', 'Нобай сақталды.'], 'Предложение отправлено заказчику.': ['Proposal sent to client.', 'Ұсыныс тапсырыс берушіге жіберілді.'], 'Этап отправлен заказчику.': ['Stage sent to client.', 'Кезең тапсырыс берушіге жіберілді.'], 'Решение сохранено.': ['Decision saved.', 'Шешім сақталды.'],
  'Предложение команды:': ['Team proposal:', 'Команда ұсынысы:'], 'Опыт за эту работу:': ['XP from this job:', 'Осы жұмыс үшін XP:'], 'задача доступна всем командам': ['task open to all teams', 'тапсырма барлық командаға ашық'], 'Закрыть': ['Close', 'Жабу'], 'Улучшить карточку': ['Improve card', 'Карточканы жақсарту'], 'Предложения': ['Proposals', 'Ұсыныстар'], 'Предложение отправлено': ['Proposal sent', 'Ұсыныс жіберілді'], 'Подать предложение': ['Send proposal', 'Ұсыныс жіберу'], 'Работа завершена': ['Job complete', 'Жұмыс аяқталды'], 'Показать следующий этап': ['Submit next stage', 'Келесі кезеңді ұсыну'], 'Этап ожидает подтверждения': ['Stage awaiting approval', 'Кезең растауды күтуде'], 'Три этапа выполнены': ['Three stages completed', 'Үш кезең орындалды'],
  'Предложения команд': ['Team proposals', 'Командалар ұсыныстары'], 'Можно выбрать несколько команд или оставить все без выбора.': ['You can select several teams or leave all unselected.', 'Бірнеше команданы таңдауға немесе ешкімді таңдамауға болады.'], 'Выбрано': ['Selected', 'Таңдалды'], ' из ': [' of ', ' ішінен '], 'Завершено': ['Completed', 'Аяқталды'], 'Отклонено': ['Rejected', 'Қабылданбады'], 'Ожидает': ['Pending', 'Күтуде'], 'Идея:': ['Idea:', 'Идея:'], 'План:': ['Plan:', 'Жоспар:'], 'Материалы': ['Materials', 'Материалдар'], 'Этап': ['Stage', 'Кезең'], 'Подтверждён, +10 XP': ['Approved, +10 XP', 'Расталды, +10 XP'], 'Ожидает подтверждения': ['Awaiting approval', 'Растауды күтуде'], 'Результат': ['Result', 'Нәтиже'], 'Подтвердить этап': ['Approve stage', 'Кезеңді растау'], 'Работа завершена · бонус +30 XP': ['Job complete · +30 XP bonus', 'Жұмыс аяқталды · +30 XP бонус'], 'Отклонить': ['Reject', 'Қабылдамау'], 'Снять выбор': ['Deselect', 'Таңдауды алып тастау'], 'Выбрать': ['Select', 'Таңдау'], 'Завершить работу · +30 XP': ['Complete job · +30 XP', 'Жұмысты аяқтау · +30 XP'], 'Предложений пока нет.': ['No proposals yet.', 'Әзірге ұсыныс жоқ.'],
  'Отчёт команды': ['Team report', 'Команда есебі'], 'Показать выполненный этап': ['Submit completed stage', 'Орындалған кезеңді ұсыну'], '10 XP появятся после подтверждения заказчиком.': ['10 XP will be awarded after client approval.', 'Тапсырыс беруші растаған соң 10 XP беріледі.'], 'Что выполнено': ['Work completed', 'Орындалған жұмыс'], 'Ссылка на результат': ['Result link', 'Нәтиже сілтемесі'], 'Отмена': ['Cancel', 'Бас тарту'], 'Отправить на подтверждение': ['Submit for approval', 'Растауға жіберу'], 'Отправить': ['Send', 'Жіберу'],
  'Опишите, что происходит сейчас и какую проблему нужно решить.': ['Describe what happens now and what problem needs solving.', 'Қазір не болып жатқанын және қандай мәселені шешу керегін сипаттаңыз.'], 'Назовите конкретные данные, примеры или материалы для команды.': ['Provide concrete data, examples, or materials for the team.', 'Командаға нақты деректерді, мысалдарды не материалдарды көрсетіңіз.'], 'Опишите конкретный результат, который команда должна передать.': ['Describe the specific deliverable expected from the team.', 'Команда тапсыратын нақты нәтижені сипаттаңыз.'], 'Укажите, по каким признакам заказчик примет результат.': ['State how the client will accept the result.', 'Тапсырыс беруші нәтижені қандай белгілермен қабылдайтынын көрсетіңіз.'], 'Уточните срок, условия работы или ограничения.': ['Clarify timing, work conditions, or constraints.', 'Мерзімді, жұмыс шарттарын не шектеулерді нақтылаңыз.'], 'Назовите группу людей, для которых нужно решение.': ['Name the people who need the solution.', 'Шешім қажет адамдар тобын атаңыз.'], 'Укажите человека или канал для обратной связи.': ['Give a person or channel for feedback.', 'Кері байланыс беретін адамды не арнаны көрсетіңіз.'], 'Замените заглушку конкретным ответом.': ['Replace the placeholder with a concrete answer.', 'Орынбасар мәтінді нақты жауаппен ауыстырыңыз.'],
  'Заполните поле': ['Fill in the field', 'Өрісті толтырыңыз'], 'баллов после подтверждения': ['points after confirmation', 'растаудан кейін ұпай'], 'баллов': ['points', 'ұпай'], 'балла': ['points', 'ұпай'], 'балл': ['point', 'ұпай'], 'Засчитано:': ['Counted:', 'Есептелді:'], 'Засчитано': ['Counted', 'Есептелді'], 'рейтинг без изменения': ['score unchanged', 'рейтинг өзгермеді'], 'место №': ['rank #', 'орын №'], 'Место в каталоге:': ['Catalog rank:', 'Каталогтағы орын:'], 'Новый уровень:': ['New level:', 'Жаңа деңгей:'], 'Карточка подтверждена:': ['Card confirmed:', 'Карточка расталды:'],
  'задача': ['task', 'тапсырма'], 'задачи': ['tasks', 'тапсырма'], 'задач': ['tasks', 'тапсырма'], 'предложение': ['proposal', 'ұсыныс'], 'предложения': ['proposals', 'ұсыныс'], 'предложений': ['proposals', 'ұсыныс'], 'черновика': ['drafts', 'нобай'], 'черновиков': ['drafts', 'нобай'], 'участник': ['member', 'қатысушы'], 'участника': ['members', 'қатысушы'], 'участников': ['members', 'қатысушы'], 'Команда': ['Team', 'Команда'],
  'Открыта': ['Open', 'Ашық'], 'Есть предложения': ['Has proposals', 'Ұсыныстар бар'], 'Команда выбрана': ['Team selected', 'Команда таңдалды'], 'Есть завершённые работы': ['Has completed work', 'Аяқталған жұмыс бар'], 'Завершена': ['Completed', 'Аяқталды'],
  'Язык интерфейса': ['Interface language', 'Интерфейс тілі'], 'Запросы к OpenAI · модель:': ['OpenAI requests · model:', 'OpenAI сұраулары · модель:'], 'XP команды': ['Team XP', 'Команда XP'], 'ранг': ['rank', 'дәреже'], 'Старт': ['Start', 'Бастау'], 'этап подтверждён': ['stage approved', 'кезең расталды'], 'этапа подтверждены': ['stages approved', 'кезең расталды'], 'этапов подтверждено': ['stages approved', 'кезең расталды'], 'работа завершена': ['job completed', 'жұмыс аяқталды'], 'работы завершены': ['jobs completed', 'жұмыс аяқталды'], 'работ завершено': ['jobs completed', 'жұмыс аяқталды'],
  'Ещё': ['Another', 'Тағы'], 'до уровня': ['to level', 'деңгейге дейін'], 'До уровня': ['To level', 'Деңгейге дейін'], 'осталось': ['remaining', 'қалды'], 'Опыт за результат': ['XP for results', 'Нәтиже үшін XP'], 'выбрано': ['selected', 'таңдалды'], 'отклонено': ['rejected', 'қабылданбады'], 'ожидает решения': ['awaiting decision', 'шешімді күтуде'], 'ожидает подтверждения': ['awaiting approval', 'растауды күтуде'], '+10 XP подтверждено': ['+10 XP approved', '+10 XP расталды'], 'бонус': ['bonus', 'бонус'],
  'Идея решения': ['Solution idea', 'Шешім идеясы'], 'План работы': ['Work plan', 'Жұмыс жоспары'], 'Например, 10 дней': ['For example, 10 days', 'Мысалы, 10 күн'], 'Ссылка на прототип или материалы': ['Prototype or materials link', 'Прототип не материалдар сілтемесі'], 'Новое предложение': ['New proposal', 'Жаңа ұсыныс'], 'Предложение для задачи': ['Proposal for task', 'Тапсырмаға ұсыныс'], 'Предложить решение': ['Propose a solution', 'Шешім ұсыну'], 'Следующие поля:': ['Next fields:', 'Келесі өрістер:'],
  'Восстановлена незаконченная карточка из этого браузера.': ['Unfinished card restored from this browser.', 'Аяқталмаған карточка осы браузерден қалпына келтірілді.'], 'Не удалось сохранить в браузере. Используйте «Сохранить черновик».': ['Could not save in this browser. Use “Save draft”.', 'Браузерде сақтау мүмкін болмады. «Нобайды сақтау» түймесін қолданыңыз.'],
  'Не удалось подготовить черновик.': ['Could not prepare the draft.', 'Нобайды дайындау мүмкін болмады.'], 'Не удалось получить вопросы.': ['Could not get questions.', 'Сұрақтарды алу мүмкін болмады.'], 'Ответы добавлены. Проверьте их и подтвердите карточку.': ['Answers added. Review and confirm the card.', 'Жауаптар қосылды. Оларды тексеріп, карточканы растаңыз.'],
  'Этап подтверждён. Команда получила 10 XP.': ['Stage approved. The team earned 10 XP.', 'Кезең расталды. Команда 10 XP алды.'], 'Работа завершена. Команда получила ещё 30 XP.': ['Job completed. The team earned another 30 XP.', 'Жұмыс аяқталды. Команда тағы 30 XP алды.'],
  'Сбросить задачи, черновики и предложения к демонстрационным данным? Текущее состояние сохранится в data/backups.': ['Reset tasks, drafts, and proposals to demo data? The current state will be saved in data/backups.', 'Тапсырмаларды, нобайларды және ұсыныстарды демо деректерге қайтару керек пе? Ағымдағы күй data/backups қалтасында сақталады.'],
  'OpenAI вернул неполный список вопросов.': ['OpenAI returned an incomplete question list.', 'OpenAI толық емес сұрақтар тізімін қайтарды.'], 'OpenAI вернул неполный черновик. Попробуйте ещё раз.': ['OpenAI returned an incomplete draft. Try again.', 'OpenAI толық емес нобай қайтарды. Қайталап көріңіз.'], 'OpenAI не вернул корректный черновик. Попробуйте ещё раз.': ['OpenAI returned an invalid draft. Try again.', 'OpenAI жарамсыз нобай қайтарды. Қайталап көріңіз.'], 'OpenAI не успел завершить черновик. Попробуйте ещё раз.': ['OpenAI could not finish the draft. Try again.', 'OpenAI нобайды аяқтай алмады. Қайталап көріңіз.'], 'OpenAI API вернул ошибку': ['OpenAI API returned an error', 'OpenAI API қате қайтарды'],
  'Выбор команды с отправленными этапами нельзя отменить.': ['You cannot deselect a team after it has submitted a stage.', 'Кезең жіберген команданың таңдауын алып тастауға болмайды.'], 'Для одной работы можно отправить не более трёх этапов.': ['A job can have at most three submitted stages.', 'Бір жұмысқа ең көбі үш кезең жіберуге болады.'], 'Добавьте хотя бы одно сведение о задаче.': ['Add at least one detail about the task.', 'Тапсырма туралы кемінде бір мәлімет қосыңыз.'], 'Завершённую работу нельзя изменить.': ['A completed job cannot be changed.', 'Аяқталған жұмысты өзгертуге болмайды.'],
  'Задача не найдена.': ['Task not found.', 'Тапсырма табылмады.'], 'Команда не найдена.': ['Team not found.', 'Команда табылмады.'], 'Неверный формат JSON.': ['Invalid JSON format.', 'JSON пішімі қате.'], 'Неизвестное действие.': ['Unknown action.', 'Белгісіз әрекет.'], 'Нет этапа для подтверждения.': ['No stage to approve.', 'Растайтын кезең жоқ.'], 'Подтвердите сброс демонстрационных данных.': ['Confirm the demo reset.', 'Демо деректерді қалпына келтіруді растаңыз.'], 'Подтвердите точность сведений перед публикацией.': ['Confirm the information before publishing.', 'Жариялар алдында мәліметтердің дұрыстығын растаңыз.'], 'Подтвердите хотя бы один этап перед завершением.': ['Approve at least one stage before completing the job.', 'Жұмысты аяқтар алдында кемінде бір кезеңді растаңыз.'], 'Предложение не найдено.': ['Proposal not found.', 'Ұсыныс табылмады.'],
  'Работа уже завершена или команда не выбрана.': ['The job is complete or the team has not been selected.', 'Жұмыс аяқталған немесе команда таңдалмаған.'], 'Работа уже завершена.': ['The job is already complete.', 'Жұмыс әлдеқашан аяқталған.'], 'Слишком большой запрос.': ['Request too large.', 'Сұрау тым үлкен.'], 'Сначала дождитесь решения по предыдущему этапу.': ['Wait for a decision on the previous stage.', 'Алдыңғы кезең бойынша шешімді күтіңіз.'], 'Сначала заказчик должен выбрать команду.': ['The client must select the team first.', 'Алдымен тапсырыс беруші команданы таңдауы керек.'], 'Сначала подтвердите ожидающий этап.': ['Approve the pending stage first.', 'Алдымен күтіп тұрған кезеңді растаңыз.'], 'Ссылка должна начинаться с http:// или https://.': ['The link must start with http:// or https://.', 'Сілтеме http:// немесе https:// деп басталуы керек.'], 'Эта команда уже отправила предложение.': ['This team has already sent a proposal.', 'Бұл команда ұсыныс жіберіп қойған.'], 'Ошибка сервера.': ['Server error.', 'Сервер қатесі.'],
  'Ошибка запроса.': ['Request failed.', 'Сұрау қатесі.'], 'Не удалось сохранить изменение.': ['Could not save the change.', 'Өзгерісті сақтау мүмкін болмады.'], 'Не удалось загрузить каталог:': ['Could not load catalog:', 'Каталогты жүктеу мүмкін болмады:'], 'Запустите сервер и обновите страницу.': ['Start the server and refresh the page.', 'Серверді іске қосып, бетті жаңартыңыз.'],
  'OpenAI не принял API ключ.': ['OpenAI did not accept the API key.', 'OpenAI API кілтін қабылдамады.'], 'OpenAI вернул некорректный ответ.': ['OpenAI returned an invalid response.', 'OpenAI жарамсыз жауап қайтарды.'], 'OpenAI не успел завершить ответ. Попробуйте ещё раз.': ['OpenAI did not finish. Try again.', 'OpenAI жауапты аяқтай алмады. Қайталап көріңіз.'], 'OpenAI отвечает слишком долго.': ['OpenAI is taking too long.', 'OpenAI тым ұзақ жауап беруде.'], 'Ваш текст остался в форме; повторите запрос.': ['Your text remains in the form; retry.', 'Мәтініңіз пішінде сақталды; сұрауды қайталаңыз.']
};

const entries = Object.entries(phrases).sort((a, b) => b[0].length - a[0].length);
let language = languages[localStorage.getItem('hackalem-language')] ? localStorage.getItem('hackalem-language') : 'ru';
const textCache = new WeakMap();
const attrCache = new WeakMap();

export function currentLanguage() { return language; }
export function canonicalCategory(value) {
  for (const ru of ['Веб-разработка', 'Дизайн', 'Исследование']) {
    if ([ru, ...phrases[ru]].includes(value)) return ru;
  }
  return value;
}
export function translate(source) {
  if (language === 'ru') return String(source);
  let result = String(source);
  const column = language === 'en' ? 0 : 1;
  const levelName = name => phrases[name]?.[column] || name;
  result = result.replace(/Ещё (\d+) баллов до уровня «([^»]+)»/g, (_, points, name) =>
    language === 'en' ? `${points} more points to reach “${levelName(name)}”` : `«${levelName(name)}» деңгейіне дейін тағы ${points} ұпай`);
  result = result.replace(/До уровня «([^»]+)» осталось (\d+) баллов/g, (_, name, points) =>
    language === 'en' ? `${points} points to reach “${levelName(name)}”` : `«${levelName(name)}» деңгейіне дейін ${points} ұпай қалды`);
  // Exact phrases and recurring fragments cover both static labels and score messages with numbers.
  for (const [ru, values] of entries) if (result.includes(ru)) result = result.replaceAll(ru, values[column]);
  return result;
}

function localizeNode(node) {
  if (!node.nodeValue?.trim() || node.parentElement?.closest('script,style,textarea')) return;
  if (node.parentElement?.closest('.user-copy, #cards .card > p, #cards .card h3, .recommendation-card h3, .card .company, .card .chip')) return;
  const cached = textCache.get(node);
  const original = cached && node.nodeValue === cached.translated ? cached.original : node.nodeValue;
  const translated = translate(original);
  textCache.set(node, { original, translated });
  if (node.nodeValue !== translated) node.nodeValue = translated;
}

export function localizePage(root = document.body) {
  document.documentElement.lang = language === 'kk' ? 'kk' : language;
  document.title = language === 'en' ? 'Start — tasks that find their team' : language === 'kk' ? 'Старт — өз командасын табатын тапсырмалар' : 'Старт — задачи, которые находят свою команду';
  for (const option of root.querySelectorAll('option:not([value])')) {
    const firstText = [...option.childNodes].find(node => node.nodeType === Node.TEXT_NODE);
    const original = textCache.get(firstText)?.original || option.textContent.trim();
    option.setAttribute('value', original);
  }
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
  while (walker.nextNode()) localizeNode(walker.currentNode);
  for (const element of [root, ...root.querySelectorAll('[placeholder],[aria-label],[title],option')]) {
    const previous = attrCache.get(element) || {};
    const next = {};
    for (const name of ['placeholder', 'aria-label', 'title']) {
      if (!element.hasAttribute(name)) continue;
      const actual = element.getAttribute(name);
      const original = previous[name] && actual === previous[name].translated ? previous[name].original : actual;
      const translated = translate(original);
      next[name] = { original, translated };
      if (actual !== translated) element.setAttribute(name, translated);
    }
    if (Object.keys(next).length) attrCache.set(element, next);
  }
}

export function setLanguage(next) {
  if (!languages[next]) return;
  language = next;
  localStorage.setItem('hackalem-language', next);
  localizePage();
}

const observer = new MutationObserver(() => localizePage());
export function startLocalization() {
  localizePage();
  observer.observe(document.body, { childList: true, characterData: true, subtree: true });
}
